version: '3'

services:

  sensor-reader:
    container_name: sensor-reader
    restart: always
    build:
      context: ./sensor-reader
    hostname: sensor-reader
    ports:
      - 20000:20000
    networks:
      - backend

  db-sensor-reader:
    container_name: sensor-reader
    restart: always
    image: postgres:12.2-alpine
    hostname: sensor-reader
    volumes:
      - db-sensor-reader:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=sensor-reader
      - POSTGRES_PASSWORD=sensor-reader
      - POSTGRES_DB=sensor-reader
    networks:
      - backend

networks:
  backend:
  frontend:

volumes:
  db-sensor-reader:
