mqtt:
  host: "d427e1f50e8041e4af18d3125fd0dc91.s1.eu.hivemq.cloud"
  port: 8883
  username: phoenigm
  password: Qwerty123
  topic: test/topic
  clientId: sensor-reader
server:
  port: ${PORT:20000}
